apiVersion: apps/v1
kind: Deployment
metadata:
  name: dominio-contoso-com
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
      tier: frontend
  template:
    metadata:
      labels: 
        app: client
        tier: frontend
    spec:
      containers:
      - name: dominio-contoso-com
        image: wordpress
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            secretKeyRef:
              name: dominio-contoso-keys
              key: db-host
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: dominio-contoso-keys
              key: db-name
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: dominio-contoso-keys
              key: db-username
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dominio-contoso-keys
              key: db-password
        volumeMounts:
        - mountPath: "/var/www/html"
          name: dominio-contoso-com-volume
      volumes:
      - name: dominio-contoso-com-volume
        persistentVolumeClaim:
          claimName: pvc-dominio-contoso-com
