apiVersion: v1
kind: Service
metadata:
  name: dominio-contoso-com
  labels:
    app: client
spec:
  selector:
    app: client
    tier: frontend
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
