apiVersion: v1
kind: PersistentVolume
metadata:
  name: segundo-pv
  namespace: lupalinda
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/dados2
    server: 187.84.232.54
    readOnly: false
