apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: primeirajob
  name: primeirajob
  namespace: default
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        job-name: primeirajob
    spec:
      containers:
      - command:
        - java,
        - -cp,
        - /,
        - RandomRunner,
        - /numbers.txt,
        - "10000"
        image: k8spatterns/random-generator:1.0
        imagePullPolicy: IfNotPresent
        name: primeirajob
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
